#!/bin/bash

#Copyright (c) 2020-2021 Huawei Device Co., Ltd.
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

#set -e

OUT_DIR="out/arm_virt/display_qemu/"
sudo modprobe mtdram total_size=65536 erase_size=256
sudo mtdpart add /dev/mtd0 kernel 0 10223616
sudo mtdpart add /dev/mtd0 bootargs 10223616 262144
sudo mtdpart add /dev/mtd0 root 10485760 23068672
sudo mtdpart add /dev/mtd0 user 33554432 33554432
sudo nandwrite -p /dev/mtd1 $OUT_DIR/liteos.bin
echo -e "bootargs=root=cfi-flash fstype=jffs2 rootaddr=10M rootsize=22M useraddr=32M usersize=32M\x0" | sudo nandwrite -p /dev/mtd2 -
sudo nandwrite -p /dev/mtd3 $OUT_DIR/rootfs_jffs2.img
sudo nandwrite -p /dev/mtd4 $OUT_DIR/userfs_jffs2.img
sudo dd if=/dev/mtd0 of=flash.img
sudo chown `whoami` flash.img
sudo rmmod mtdram

sudo modprobe tun tap
sudo ip link add br0 type bridge
sudo ip address add 10.0.2.2/24 dev br0
sudo ip link set dev br0 up

echo ready to start qemu
