#!/bin/bash

#Copyright (c) 2020-2021 Huawei Device Co., Ltd.
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

set -e

product_path=`hb env|grep 'product path:'`
real_cmd="${product_path:26}/qemu_run.sh"
if [[ ! -x "${real_cmd}" ]]; then
    echo -e "Failed: ${real_cmd}"
    echo -e "Using 'hb set' to choose supported QEMU board\n"
    exit
fi

board=`hb env|grep 'board:'`
echo -e "board:${board:18}\n"
exec $real_cmd $@

